language: node_js
node_js:
- 8.11.1
branches:
  only:
  - develop
cache:
  directories:
  - node_modules
before_install:
- npm install -g mocha
- npm install
script:
- npm run test
after_success:
- npm run coveralls
after_script:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: heroku
  app: my-diary-dev
  api_key:
    secure: Ym9GfHqK4ptbP0SwbJYEWGdWxQr3sO48bHsH4a+Wp17vu2YHCRNUTX84gM3yNy0lB2U1KI2sskgjvFlPdVc0UfzUrjFPcvct6iz2DKyCiaxOd8wRRn+n9MjSmifpIDIyYiuZEJfrGuyV02zr+LManY4S9IKLfhl3WoGfeipElRq18DdZna14iJ8Zdpis9A8qY7rkYYDI4MfY+ZimDYuggQ9wMQvD7kI980fFa3dG0mFgMG0JzEPvlTu757VAfRo/GyCAeIYu/LZkR2hx0XCNcd7F/oe9wVM7VcbnnUEyL4AhISeLPgp1e7mB49X2rLZ+x6pd/WvrAtsdZzt9hJEkA9b4G97n9SN465szrm0+/cn3sn2/f5rbbAYNODZKgps0N+DAME0v46X9BA/Lxa2fpa1uHDgKZoSszGnDvIPEQghfczgS+NFnm/515+J74+Le/v3fJI0KubQWxX/3Qsos2GnVm0C6NM0ATbZsQ6wiT1BdL+gC2GopS9GuFAf0irWzd2R9T6ykZk938S+JIfYN5AQuzstT4MZQ/cXV6laVHotyYqCEyiFo8aG+o0xASd24d+c9OlbvqSA4+9vV760g2NZ7dHuojxbsTyJkhFG+HjuXaMHdReWPN53f8ElJKRB3oLIKblNu4aNiGBEKCWnXfddqP46qTa5FFjgDOyd6NFk=
  on:
    repo: Victor-Ugwueze/MyDiary
    branch: develop
