language: node_js
node_js:
- 8.11.1
branches:
  only:
  - develop
cache:
  directories:
  - node_modules
before_install:
- npm install -g mocha
- npm install
script:
- npm run test
after_success:
- npm run coveralls
after_script:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: heroku
  app: my-diary-dev
  api_key:
    secure: wFz11kTyI8BCMfsTsASKSzC9bBi6qBlOnv21VuI7hk00aTsz6XeUxcw15wRJ8v+2DCAgYDy2eDaUIsB3I2jSPH8UXir/chfMbX8fBSVbIi7ZaXuediugG9eRwfHlFi47Xi9OlFv0Qk0Uaveglh5B4qYX1tk/lkKCajK7m8X7Vae6kpDszfrv+tJko9nTJX+/5wXubmSn938dEr/ajJfjChayMMuQfwrgwIJjxByeJMQjLF20ZEZ7Iefo072lj4IeXP05Vh2YU7uQTAqP/lpTvrg/Skgsa4xgyq5+7RuYieWVlNFdZQrvduoRlQmlWcng2Tzwaf1Blo/h7C/D7TOLiMlnVGGPEG7Nj2g52X4gKA1shkn6bM728FXS7UgLODxf0GGNfVB4pEsPtKd0BkdhHn3Kfv0rxwWkSDMn/DFCCxArAWI/VXfdpF4oDL+IEz3oQxqz9bzTd3GT+oKRiPjJFbJS9UmGdW8xADNPXPrRcJueZGjdQRz4bGffTiuHb39Hxw57AYEurPfAupLrnZf2uZliHf8WTHWAEbJcKTADE9vWpi+/yA19Wo4Em8ebK9WfkY0seZpjlAg37QtSxDcvVZYRbCJ3KEmb8ugiQo9bn/v1FwWDzrd8wqAb4R+WgVkcyPFU+g+Fxq4WO1s+QXNSofjxFMOkDF5RkRc66v6hkec=
  on:
    repo: Victor-Ugwueze/MyDiary
    branch: develop
