language: node_js
node_js:
- 8.11.1
branches:
  only:
  - develop
cache:
  directories:
  - node_modules
before_install:
- npm install -g mocha
- npm install
script:
- npm run test
after_success:
- npm run coveralls
after_script:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: heroku
  app: my-diary-dev
  api_key:
    secure: xRMHynyZWLAfVf3wLtcVStQujYAfn93+MENKNIgpMND6AI7s1wqKzM5abtgbt1b1QbzWWsAHGcWQgzWS1L2qdslK4oeEyHCeZ5aaoHITIjRixstYxYwGAN88aSMrm2DT7WTxkegQhnJBAo5+JC6mAS+DZCBB0IbLn6+vJn4GYqNPLhpf7GOg6LAxNtJmHJxKAP/kuxOQyj6jE/d3HgETDVEqcXiaMMQFN47yqYFd8m61lTZjCFBUPTVf6Omck+7cILw4sSWpWjWB4EZLyiz44Mpj9hgaf0MDog5Xx+otm4rEhKWFcOeYXInsLApRaWvxEV9FcCdFz+slfQtmgPRMt58nlhb/k/2t1zDEyIpYyY0PP1LKOpSeSCM89MPXFfss0WhgjL+PaHK3A6Hy5+Grr3WZPO8njHYRpPfkb1/iNEUnfef/A85idPACblpoHJttNvpZT3AF20wSkwk9uL6jY7QuzzurswhBHsiiFXsiQjs5eI7XiD+z/zdCMSS//dP7561vsgRkckNkoN0ikpjAZ+ZfcvM7nhE6gAfYmMeGueLEEQ+lFEYf9n+P/dwsCSh8a02QiD5CuYBGQpNalAoBsmw1GTlBJ4MlOWS5XA5HfDqpUiY7WHTRqPEoxPXAXw0JSGmTNH+4ZfqD16YrLiM+i9gI/CmDKuIc2g4YZbQw2Bo=
  on:
    repo: Victor-Ugwueze/MyDiary
    branch: develop
