language: node_js
node_js:
- 8.11.1
branches:
  only:
  - develop
cache:
  directories:
  - node_modules
before_install:
- npm install -g mocha
- npm install
script:
- npm run test
after_success:
- npm run coveralls
after_script:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: heroku
  app: my-diary-dev
  api_key:
    secure: lX0H3JDQnErPr01L08REgc4TNrfXyLWXFWNwamDQjEaWuQV9Rif8Zuw+NrQXKxPf8Bjg5S6BFVCg6P3uYIPzyND1Xdo0knb1nDcKj4kicQUWG3UQkYVSyKYc503rMMM2YiT7UX6wW3bu+edgGwXHy+FnR+MEGcqU8BcmyOYjaAujKX7HXZyybzMSlDQ0TdEUT3CHmF67u7YmBlJaz+NzwYUOelMrPUzB/RGWCRX+yuiexJxcC0Klk5E7IcxgZcba93CPGriFRWnacSURAur8W/ajx2mBQ6Zd2wTXFrXLlMUezWCFwVACsjoe5OKcpsFuR3wPxkhf+XQDj/Kt7aFYMflzwW7bgq0qgg51pRxQeUb1Iu0eceTyl/62atHZWvr3TrLJF0UeRDETGfUUQvOOaB1uinlAETFhqQ1QKZqMcqkRMFOdWZ4G40Mql09Osv3TIgCNtqmK8y0tRepktvfpkJAhRWxhAwU7nMDG8GF0MMgF7G2maLB2sk7jZq69tPnYolOkxj2gt6f65LkEtVxJJB0Ys3JJwCUCpU58keBhQ/Wh043T7sttt6ywIzueLt84OVPMy1+MLSHH3t35ACsEhv+UJXacDz77SkywCyN23Whv9mixa8q1Fu6RC5uo8RyyHhgGE2c6ijGsh0esA1wA57WIT5oTB/zbAXEZ8E85TE4=
  on:
    repo: Victor-Ugwueze/MyDiary
    branch: develop
