language: node_js
node_js:
- 8.11.1
branches:
  only:
  - develop
cache:
  directories:
  - node_modules
before_install:
- npm install -g mocha
- npm install
script:
- npm run test
after_success:
- npm run coveralls
after_script:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: heroku
  app: my-diary-dev
  api_key:
    secure: ysAjpEmKVN3ikwdgxXDWdzP/E5ebzbQHNni96yWql5BMM1fyHgx1B7/fLoHmlFbO3xc41t5TlcglCwD4q7CzxSvyB1V/ivY07JwKlGyRtcvDKCZRpL1zGY/fNf2wu8H0feXX986pb1dU+WBlZybm7iVOfwcJc9yivf15nyFcZ78BDsLnxlRiTPyqUIg1jy8NJLcMBDUMOv29dKmu6LdhPY3ThFaN4IbXFS2ywkglZHm6NrBHjKm/TrJwabKzZ0CQny5JveDT4L27CdUxJfVsZQpfFA/QzsKcDCu+xfe40pV/TxMjUjWAcfL1Q0Xm29oV9VHZoEm4mxXrse4PJCsuE2mG30mW28vao6QAqM/KrvWlfgweEFkPbOcle/bIGTOQ0MyiBheJmO3fpe7L2+Kn8SVa4DvgkBVfQ0JuK1/5UOdru9yp0jod2+gMtf1APVH1BILpGLo1R8MjmS+ZriWsIyQOs2+xZbpQlcVho+naKLbBjXnqQ4K621GAfhv7UPjCu2Fj2aUKtLu70KxFJhrdEpLX9PcXl62GGM/JV5g9ttBITbn1kru50iXoIo+I1RTV6MDaDdgzTsryhmg6kG7KSsAbvsMInE9IDSqD+TiG1QjTusMS92RQVCUPckCQIAy61DaRh6iRu5U/O66E6CsgiTXkCkEE4dJsb5Qh9lo6jmc=
  on:
    repo: Victor-Ugwueze/MyDiary
    branch: develop
